name: Frontend Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "frontend/**"
      
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::833090513321:role/cloudtask-frontend-deploy
          aws-region: us-east-1
    
      - name: Generate frontend config
        run: |
          cat > frontend/config.js <<'EOF'
          window.APP_CONFIG = {
              COGNITO_DOMAIN: "https://us-east-1zdwwiqewg.auth.us-east-1.amazoncognito.com",
              CLIENT_ID: "6l2ghaere82ejr5e3cu9o0qvtd",
              REDIRECT_URI: "https://d3uuyg0mq27sk6.cloudfront.net",
              API_URL: "https://ivg0e0r24h.execute-api.us-east-1.amazonaws.com/tasks"
          };
          EOF
      
      - name: Check frontend JavaScript syntax
        run: |
          node --check frontend/config.js
          node --check frontend/app.js

      - name: Sync frontend to S3
        run: |
          aws s3 sync frontend/ s3://cloudtask-frontend-ethem/frontend/ --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id EONFCY5W9BRLN \
            --paths "/*"