name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::833090513321:role/cloudtask-frontend-deploy
          aws-region: us-east-1

      - name: Sync frontend to S3
        run: |
          aws s3 sync frontend/ s3://cloudtask-frontend-ethem/frontend/ --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id EONFCY5W9BRLN \
            --paths "/*"